#ifndef BCSDKCOMMON_H
#define BCSDKCOMMON_H

#include <QtCore/qglobal.h>

#if defined(STE15QSTEBOARDCOMPUTERSDK_LIBRARY)
#  define STE15QSTEBOARDCOMPUTERSDKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STE15QSTEBOARDCOMPUTERSDKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BCSDKCOMMON_H

